// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmjcvgxemdpgwkjztark.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndtamN2Z3hlbWRwZ3dranp0YXJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNzAxODYsImV4cCI6MjA3MTk0NjE4Nn0.x6iNVDv7ZfcK4E4b7y7B9EuwoBJLnoB6M0XWRblJqU0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});